config/routes.rb
Rails.application.routes.draw do
  resources :user_tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'user_tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user_task.rb
class UserTask < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]

  # GET /user_tasks
  # GET /user_tasks.json
  def index
    # @user_tasks = UserTask.all
  end

  # GET /user_tasks/1
  # GET /user_tasks/1.json
  def show
  end

  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # GET /user_tasks/1/edit
  def edit
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = UserTask.new(user_task_params)
    @user_task.due = fix_date(params[:user_task][:due])

    respond_to do |format|
      if @user_task.save
        # format.html { redirect_to @user_task, notice: 'User task was successfully created.' }
        format.js
        # format.json { render :show, status: :created, location: @user_task }
      else
        # format.html { render :new }
        format.js { render :new }
        # format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    respond_to do |format|
      if @user_task.update(user_task_params)
        # format.html { redirect_to @user_task, notice: 'User task was successfully updated.' }
        format.js
        # format.json { render :show, status: :ok, location: @user_task }
      else
        # format.html { render :edit }
        format.js { render :edit }
        # format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tasks/1
  # DELETE /user_tasks/1.json
  def destroy
    @user_task.destroy
    respond_to do |format|
      # format.html { redirect_to user_tasks_url, notice: 'User task was successfully destroyed.' }
      # format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = UserTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due)
    end

    def all_tasks
      @user_tasks = UserTask.all.order(:due)
    end

    def fix_date(due_date)
      date_array = due_date.split('-')
      due_date = date_array.insert(0, date_array.pop).join('-')
      Date.parse(due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_tasks/_datepicker.js.erb
$(document).ready(function() {
 $('#user_task_due').datepicker({
  autoclose: true,
  todayHighlight: true,
  toggleActive: true,
  format: "mm-dd-yyyy",
  orientation: "bottom auto"
 });
});

app/views/user_tasks/_form.html.erb
<div class="container centered">
 <%= simple_form_for(@user_task, remote: true) do |f| %>
   <%= f.error_notification %>

   <div class="form-inputs">
     <%= f.input :description, placeholder: 'Type what you gotta do here!' %>
     <%= f.input :due, as: :string, placeholder: 'Today, Junior' %>
   </div>

   <div class="form-actions">
     <%= f.submit 'Create New To Do', class: 'btn btn-info btn-sm pull-left' %>

   </div>

 <% end %>
 <button id="minimize" class="btn btn-sm btn-warning">Nevermind</button>
 <br>
 <br>
</div>

app/views/user_tasks/_user_task.html.erb
<div class="well">
 <%= link_to user_task.description, user_task, remote: true, method: :delete, data: { confirm: "You Really Did That?! Great Job!!"} %>

 <%= link_to fa_icon('pencil'), edit_user_task_path(user_task), remote: true %>
 <%#= link_to fa_icon('check-square-o'), user_task,  %>

 <div class="pull-right">
  <%= user_task.due.stamp('Monday, January, 15th') if user_task.due %>

 </div>
</div>

app/views/user_tasks/create.js.erb
$('#tasks').html("<%= j ( render @user_tasks ) %>");

$('#task-form').slideUp(350);

app/views/user_tasks/destroy.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form', user_task: @user_task %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/edit.js.erb
$('#task-form').html("<%= j (render 'form') %>").slideDown(350);

$('#minimize').click(function() {
 $('#task-form').slideUp(350);
});

<%= render 'datepicker' %>

app/views/user_tasks/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Stuff You Gotta Do:</h1>
  <div id="task-form"></div>

  <div id="tasks">
    <%= render @user_tasks %>
  </div>

  <br>

  <%= link_to new_user_task_path, remote: true do %>
    <button class="btn btn-success btn-sm add-task">
      <%= fa_icon('plus') %> Add To Do
    </button>

  <% end %>
</div>

app/views/user_tasks/new.html.erb
<h1>New User Task</h1>

<%= render 'form', user_task: @user_task %>

<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>").slideDown(350);

$('#minimize').click(function() {
 $('#task-form').slideUp(350);
 $('.add-task').show(0);
});

$('.add-task').hide(0);

<%= render 'datepicker' %>

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/update.js.erb
$('#tasks').html("<%= j ( render @user_tasks ) %>");

$('#task-form').slideUp(350);